spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, metrics, prometheus
  info:
    env:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    mappings:
      enabled: true

security:
  jwt:
    expiration-time: 3600000
    secret-key: signatureSecret183827374628384628274628364627836482738