spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym_crm?useSSL=false
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

---
spring:
  profiles:
    active: dev

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, metrics, prometheus
  info:
    env:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    mappings:
      enabled: true
